version: '3.8'

services:
  yt-extractor:
    build: .
    image: yt-audio-extractor:latest
    container_name: yt-audio-extractor
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: persist temp directory
      - ./temp:/app/temp
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
